### ISSUE TITLE
Make prefix for build targets that run tests configurable

### ISSUE THREAD

**Issue by dummyunit** [SherAndrei/fastbuild-task-provider#2]
Currently there is a hardcoded prefix `Test-` which is used to identify build targets that run tests and add them to the "Test" task group. That prefix is not mandated by FASTBuild in any way, different projects might use different prefixes. In fact, FASTBuild itself uses `RunTests-` in its own build scripts.

So it would be nice to make this prefix configurable.

**Comment by SherAndrei** [comment]
Added ability to specify which tasks are test ones using glob pattern matching
